### ISSUE TITLE
Musical notes animation

### ISSUE THREAD

**Issue by mateoguzmana** [mateoguzmana/react-native-fiesta#10]
As part of the roadmap for Fiesta, would be great to have some musical notes animation as part of the set.

Ideally the animation can be used with the Popper component, you can use the Hearts or Balloons as examples. The animation can either be created using an SVGs as a string or SVGs built with components.

Perhaps an option to choose which musical notes would be a great addition for the component.

```typescript
<MusicNotes notes=['...'] />
```

And below an image as inspiration:

(No need for all of them, leaving it up to the contributor)

![musical notes](https://user-images.githubusercontent.com/20783123/190223116-a73c7319-379c-400b-9312-d5d2c16874ba.png)

**Comment by AyushK-101** [comment]
I would like to work on the issue

**Comment by mateoguzmana** [comment]
@AyushK-101 all yours 😀

**Comment by AyushK-101** [comment]
Will be busy for a few days, would appreciate if someone can take this up
