### ISSUE TITLE
Halloween pumpkins animation

### ISSUE THREAD

**Issue by mateoguzmana** [mateoguzmana/react-native-fiesta#11]
As part of the roadmap for Fiesta and because halloween is just around the corner, would be great to have some pumpkins animation as part of the set.

Ideally the animation can be used with the Popper component, you can use the Hearts or Balloons as examples. The animation can either be created using an SVG as a string or an SVG built with components.

Ideal API:

```typescript
<Pumpkins theme={FiestaThemes.Halloween} />
```
Below an image for inspiration:

![image](https://user-images.githubusercontent.com/20783123/190224288-46ee58e5-2a3b-48d0-94b8-0c3359dc494d.png)

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by mateoguzmana** [comment]
@AyushK-101 go for it, good luck!

**Comment by AyushK-101** [comment]
Will be busy for a few days, it would be appreciated if someone can take this up
