### ISSUE TITLE
Documentation for the Popper component

### ISSUE THREAD

**Issue by mateoguzmana** [mateoguzmana/react-native-fiesta#12]
Currently there is no documentation for the [Popper component](https://github.com/mateoguzmana/react-native-fiesta/blob/main/src/components/Popper.tsx).

This component can be very useful for custom animations. Would be good to expose the how to use it under the [components](https://mateoguzmana.github.io/react-native-fiesta/docs/category/components) section on the Fiesta website. You can follow the documentation structure of the other components

**Comment by athulmekkoth** [comment]
can i work on this ?

**Comment by mateoguzmana** [comment]
Go for it @athulmekkoth, good luck!
