### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by nextriot** [mateoguzmana/react-native-fiesta#34]
Hey, just encountered this bug when installing via yarn.
```
Command failed.
Exit code: 127
Command: patch-package
Arguments: 
```

Version 0.3.1 and below seem to install as expected, but 0.4.0 onward raises this error.

**Comment by mateoguzmana** [comment]
Thanks for this report @nextriot. I found out upon investigating that there was a patch-package config not intended to be on the published config. Removed, should work now in v0.5.1
