### ISSUE TITLE
Can not find module for react-native-fiesta

### ISSUE THREAD

**Issue by mduc-dev** [mateoguzmana/react-native-fiesta#36]
**Describe the bug**
Im trying to install this package, then appear error can not find module for react-native-fiesta, I already tried remove node_modules, yarn.lock, yarn install...

**To Reproduce**
1. Install package with 
yarn add @shopify/react-native-skia 0.1.172
yarn add react-native-fiesta 0.5.1

<img width="683" alt="Screen Shot 2023-05-20 at 12 09 09" src="https://github.com/mateoguzmana/react-native-fiesta/assets/80993895/623c1cb4-e72a-4bac-89f5-eaee4e8d74cf">

**Screenshots**
<img width="503" alt="Screen Shot 2023-05-20 at 12 04 13" src="https://github.com/mateoguzmana/react-native-fiesta/assets/80993895/c50f5da7-7ce3-4447-9c72-f69dcb042c98">

**Comment by dimaageev** [comment]
Same here, with the same versions and with Expo SDK 48

**Comment by dleavittpmc** [comment]
Y'all still having that issue? I have that same TypeScript error saying the module doesn't exist, but when I build the app everything still works great.
