### ISSUE TITLE
UI is not touchable after the animation was executed

### ISSUE THREAD

**Issue by Sailoshi** [mateoguzmana/react-native-fiesta#37]
**Describe the bug**
When an animation was executed, I can't interact with my app anymore. It's like there is an invisible Container overall. I need to restart the app.

**To Reproduce**
I am using the runFiesta hook inside a navigating container/stack together with s button onPress.

**Expected behavior**
I can still interact with my app/UI after running an animation.

Do you have any idea how such behavior occurs?

**Comment by kations** [comment]
I have the same problem using expo sdk50 beta with EmojiPopper

**Comment by mateoguzmana** [comment]
By default, the `Canvas` has pointer events that block the UI. For the `Popper`component for example, the pointer events are now disabled by default to avoid this as the Fiesta components are not intended to have pointer events – but in case you are using an individual animation that doesn't have this property, you can disable it as below:

```tsx
<Canvas pointerEvents="none">
  <YourSkiaComponent />
</Canvas>
```

Will be added to the docs as well for future reference.
