### ISSUE TITLE
Flowers animation

### ISSUE THREAD

**Issue by mateoguzmana** [mateoguzmana/react-native-fiesta#7]
It would be great to have some animated flowers in Fiesta to celebrate some special occasions. 

Ideally the animation can be used with the Popper component, you can use the Hearts or Balloons as examples. The animation can either be created using an SVG as a string or an SVG built with components.

Keeping in mind performance, perhaps the animation can include some flower opening or something else. Leaving it up to the contributor.

Leaving this [animation](https://codepen.io/Mahi-K/pen/wvqYLEL) I found in Codepen, some animated flowers with css and canvas.

And below an image as inspiration:

![image](https://user-images.githubusercontent.com/20783123/188509615-081cae89-53de-4dcc-8243-900c72cc8bda.png)

**Comment by aswinikalyan30** [comment]
Hey, I wanna take this up!

**Comment by mateoguzmana** [comment]
@aswinikalyan30 cool! go for it :)

**Comment by aswinikalyan30** [comment]
Sorry, cant work on this
